# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: autopep8-wrapper
        name: 'autopep8-wrapper (.eb)'
        types: [file]
        files: \.eb$
      - id: check-ast
        name: 'check-ast (.eb)'
        types: [file]
        files: \.eb$
      - id: autopep8-wrapper
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/pescobar/pre-commit-hooks-easybuild
    sha: master
    hooks:
      - id: check-old-easybuild-url
